name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          extra_system_packages: poppler-utils
          post_compile: |
            latexmk -pdf references.tex
            pdftotext references.pdf references.txt
      - name: Rename PDF with commit hash
        shell: bash
        run: |
          PDF_SHA="$(sha256sum main.pdf)"
          COMBINED_NAME="${GITHUB_SHA::7}-${PDF_SHA::7}"
          mv main.pdf "${COMBINED_NAME}.pdf"
          echo "ARTIFACT_NAME=${COMBINED_NAME}" >> "${GITHUB_ENV}"
          echo "PDF_NAME=${COMBINED_NAME}.pdf" >> "${GITHUB_ENV}"
      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            ${{ env.PDF_NAME }}
            references.pdf
            references.txt
